use std::fs::{create_dir_all, read_to_string, File};
use std::io::Write;

use pwvlt::Config;

use crate::error::Error;

const DEFAULT_CONFIG: &str = "# Autogenerated pwvlt config
[general]
backends = [\"nitrokey\", \"keyring\"]

[password]
length = 22
numbers = true
lowercase_letters = true
uppercase_letters = true
symbols = true
strict = true
";

pub fn load_config() -> Result<Config, Error> {
    let home = home::home_dir().ok_or(Error::HomeNotFound)?;
    // config will be loaded from ~/.config/pwvlt/config.toml
    let config_folder = home.join(".config").join("pwvlt");
    if !config_folder.exists() {
        create_dir_all(&config_folder)?;
    }
    let config_file = config_folder.join("config.toml");
    if !config_file.exists() {
        write!(File::create(&config_file)?, "{}", DEFAULT_CONFIG)?;
    }
    toml::from_str(&read_to_string(config_file)?).map_err(Error::from)
}

pub fn write_config(config: &Config) -> Result<(), Error> {
    let home = home::home_dir().ok_or(Error::HomeNotFound)?;
    write!(
        File::create(home.join(".config").join("pwvlt").join("config.toml"))?,
        "{}",
        toml::to_string(config)?
    ).map_err(Error::from)
}
